services:
  - type: web
    name: lampfire-backend
    env: docker # dockerfile 사용
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lampfire_db
          property: connectionString

databases:
  - name: lampfire_db
    plan: free
    postgresMajorVersion: 15
