services:
  - type: web
    name: lampfire-backend
    runtime: docker # dockerfile 사용
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false

      - key: DIRECT_URL
        sync: false

      - key: PORT
        value: '3000'

# databases:
#   - name: lampfire_db
#     plan: free
#     postgresMajorVersion: 15
